version: "3.7"
services:
  cornwallalliance:
    image: cornwallalliance:latest
    container_name: cornwallalliancecontainer
    environment:
      URL_ENV: "https://www.technocracy.news/"
    volumes:
      - cornwallalliance-vol:/tmp
    build:
      context: "."
      args:
        URL_ENV: "https://www.technocracy.news"
volumes:
  cornwallalliance-vol:

