version: "3.7"
services:
  bbc-non-climate:
    image: bbc:latest
    container_name: bbc-container
    environment:
      URL_ENV: "https://www.bbc.co.uk/news/topics/cp7r8vglgq1t/food"
    volumes:
      - bbc-vol:/tmp
    build:
      context: "."
      args:
        URL_ENV: "https://www.bbc.co.uk/news/topics/cp7r8vglgq1t/food"
volumes:
  bbc-vol:

