version: "3.7"
services:
  climatediscussionnexus:
    image: breitbartnews:latest
    container_name: breitbartnewscontainer
    environment:
      URL_ENV: "https://www.breitbart.com/"
    volumes:
      - breitbartnews-vol:/tmp
    build:
      context: "."
      args:
        URL_ENV: "https://www.breitbart.com/"
volumes:
  breitbartnews-vol:

